### ISSUE TITLE
Cannot set shortcut <ctrl><tab> for switch between tabs (sessions)

### ISSUE THREAD

**Issue by waldauf** [gnunn1/tilix#1487]
Hello,

I changed shortcuts and would like to set _switch to next session_ like `ctrl+tab` a to _switch to previous session_ to `ctrl+shift+tab` (like is normal in web browser). But in preferences is not possible to set it.

Yesterday I found out "accidently" your terminal emulator and have to say that I really really like it. Thx for that.

**Comment by Gabb1995** [comment]
Still doesnt work for me.

**Comment by gnunn1** [comment]
What version of tilix, it was fixed in 1.8.3

**Comment by Gabb1995** [comment]
I'm using 1.7.7, sorry I will update :+1:

**Comment by vhalis** [comment]
For anyone else who switched to tabs, I found that the proper setting is:

Preferences > Shortcuts > Window > Switch to (next|previous) session

And not:

Preferences > Shortcuts > Session > Switch to (next|previous) terminal

**Comment by soapergem** [comment]
Not sure why this issue got closed so quickly... it still doesn't work.

I'm on Ubuntu 18.04 and had "their" version of Tilix installed: 1.7.7 (which is needed because they don't have PCRE2 support), and obviously it doesn't work in that version.

I see your comment @gnunn1 in which you said this supposedly got fixed this in version 1.8.3. So on [another issue](https://github.com/gnunn1/tilix/issues/916) I found a reference to a PPA which hosts the more up-to-date versions of Tilix that are compatible with Ubuntu.

Using that PPA I've **upgraded Tilix to version 1.9.1**, but this keyboard shortcut **bug still persists**. Just so I'm communicating it clearly, here are the exact steps to reproduce the problem on Tilix 1.9.1, running on Ubuntu 18.04:

- Go into Preferences > Shortcuts
- Double-click on the shortcut key corresponding to "Switch to next session" (_the default should already be set to Ctrl+Page Down_)
- Try to enter `Ctrl+Tab`

It won't work because the Ubuntu system itself (Gnome? X11? Something else?) seems to capture that input before Tilix does, and interprets it as input that is trying to to do something invalid with the windows, because you hear the generic system sound - the same sound which normally indicates "you can't do that."

**Comment by poxin13** [comment]
Having the same issue @soapergem, Ubuntu/Gnome unable to set the shortcut for next/prev session utilizing Tab

**Comment by Gabb1995** [comment]
Yep having this issue again on a new install, cant set the next session to ctrl+tab.

**Comment by solisoares** [comment]
I figured a way to map \<ctrl\>\<tab\> in this way.
As mentioned in some comments before, \<tab\> seems to be captured in the UI not in the preferences mapping.

Since configurations are stored in dconf (https://github.com/gnunn1/tilix/issues/792), I fired up `dconf Editor`, removed the \<ctrl\>\<tab\> from default mapping and set to the tabs circulation
![image](https://github.com/gnunn1/tilix/assets/77312190/2320f8b8-ec7d-400e-9be1-d80091a4ea0a)
![image](https://github.com/gnunn1/tilix/assets/77312190/6d7ce480-3152-403f-a048-a6c6c2632785)

**Comment by ronny-rentner** [comment]
This should not be closed. It's still a problem. I cannot set CTRL-TAB to switch between sessions while for example CTRL-ESC is possible. I think this is related to Gnome/Gtk and how it records the key combination as I also couldn't set this in Gnome Terminal.

**Comment by solisoares** [comment]
Hey @ronny-rentner, have you tried the workaround of disabling ctrl-tab for switching terminal to switch session (tabs) in dconf Editor?

**Comment by ronny-rentner** [comment]
@solisoares I had tried it with dconf-editor but overlooked that there was already an existing keybinding for CTRL-TAB (for switching terminal). After removing the existing keybinding, it now works as expected via the dconf setting. Thanks for your response.

**Comment by vmojzis** [comment]
> This should not be closed. It's still a problem. I cannot set CTRL-TAB to switch between sessions while for example CTRL-ESC is possible. I think this is related to Gnome/Gtk and how it records the key combination as I also couldn't set this in Gnome Terminal.

I thought the same, but it is just a weird default shortcut binding.
The default action for "ctrl+tab" is "Focus the next terminal" (within the same tab -- no action if there is only one). "Move to next/previous Tab" is probably what you want (by default "ctrl+page up/down").

**Comment by kodingkoning** [comment]
I am having this same issue. I checked both dconf keybindings and the other shortcuts for the terminal, and there was not another CTRL-TAB binding.

I will also note that having a shortcut with a particular keybinding does not prevent it from being bound to another action.
